# Generated by Django 4.2 on 2024-10-11 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_advance_thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ECommerceBaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductsModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("l", "Liter"),
                            ("ml", "Milliliter"),
                            ("pcs", "Pieces"),
                            ("bag", "Bag"),
                            ("box", "Box"),
                            ("bottle", "Bottle"),
                            ("can", "Can"),
                            ("jar", "Jar"),
                            ("pack", "Pack"),
                            ("roll", "Roll"),
                            ("tube", "Tube"),
                            ("unit", "Unit"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                ("stock", models.FloatField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                (
                    "image_thumbnail",
                    django_advance_thumbnail.fields.AdvanceThumbnailField(
                        blank=True, null=True, upload_to="products/"
                    ),
                ),
                (
                    "unite_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
        migrations.CreateModel(
            name="ShoppingCartModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_purchased", models.BooleanField(default=False)),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
        migrations.CreateModel(
            name="ShoppingCartItemModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="ecommerce.shoppingcartmodel",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_items",
                        to="ecommerce.productsmodel",
                    ),
                ),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("payment_info", models.JSONField(blank=True, null=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="ecommerce.shoppingcartmodel",
                    ),
                ),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
        migrations.CreateModel(
            name="OrderAndShippingModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                ("shipping_address", models.TextField(blank=True, null=True)),
                (
                    "shipping_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="ecommerce.shoppingcartmodel",
                    ),
                ),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
    ]
