# Generated by Django 4.2 on 2024-10-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_shoppingcartitemmodel_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfirmationModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                (
                    "confirmation_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
                ("confirmation_info", models.JSONField(blank=True, null=True)),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
        migrations.CreateModel(
            name="PaymentRequestModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                ("mer_txnid", models.CharField(max_length=42, unique=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("payment_info", models.JSONField(blank=True, null=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="ecommerce.shoppingcartmodel",
                    ),
                ),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
        migrations.DeleteModel(
            name="PaymentModel",
        ),
        migrations.AddField(
            model_name="paymentconfirmationmodel",
            name="payment_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confirmations",
                to="ecommerce.paymentrequestmodel",
            ),
        ),
    ]
