# Generated by Django 4.2 on 2024-10-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0003_paymentconfirmationmodel_paymentrequestmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AamarPayPaymentConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pay_status",
                    models.CharField(
                        choices=[
                            ("Failed", "Failed"),
                            ("Successful", "Successful"),
                            ("Pending", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pg_txnid", models.CharField(max_length=42, unique=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("mer_txnid", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "merchant_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("store_id", models.CharField(blank=True, max_length=200, null=True)),
                ("currency", models.CharField(default="BDT", max_length=50)),
                (
                    "currency_merchant",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("conversion_rate", models.FloatField(blank=True, null=True)),
                ("store_amount", models.FloatField(blank=True, null=True)),
                ("pay_time", models.DateTimeField(blank=True, null=True)),
                ("bank_txn", models.CharField(blank=True, max_length=20, null=True)),
                ("card_number", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "card_holder",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("card_type", models.CharField(blank=True, max_length=20, null=True)),
                ("opt_a", models.CharField(blank=True, max_length=200, null=True)),
                ("opt_b", models.CharField(blank=True, max_length=200, null=True)),
                ("opt_c", models.CharField(blank=True, max_length=200, null=True)),
                ("opt_d", models.CharField(blank=True, max_length=200, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "other_currency",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("success_url", models.URLField(blank=True, null=True)),
                ("fail_url", models.URLField(blank=True, null=True)),
                (
                    "pg_service_charge_bdt",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "pg_service_charge_usd",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "pg_card_bank_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "pg_card_bank_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "risk_level",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "No risk"), (1, "May be risky")],
                        default=0,
                        null=True,
                    ),
                ),
                ("pg_error_code_details", models.TextField(blank=True, null=True)),
                ("all_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aamar_pay_payment_confirmation_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Aamar Pay Payment Confirmation",
                "verbose_name_plural": "Aamar Pay Payment Confirmations",
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mer_txnid", models.CharField(max_length=42, unique=True)),
                ("all_data", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Failed", "Failed"),
                            ("Successful", "Successful"),
                            ("Pending", "Pending"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="ecommerce.shoppingcartmodel",
                    ),
                ),
                (
                    "request_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="paymentrequestmodel",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="paymentrequestmodel",
            name="ecommercebasemodel_ptr",
        ),
        migrations.DeleteModel(
            name="PaymentConfirmationModel",
        ),
        migrations.DeleteModel(
            name="PaymentRequestModel",
        ),
        migrations.AddField(
            model_name="aamarpaypaymentconfirmation",
            name="payment_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_confirmation",
                to="ecommerce.paymentrequest",
            ),
        ),
        migrations.AddField(
            model_name="aamarpaypaymentconfirmation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aamar_pay_payment_confirmation_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
