# Generated by Django 4.2 on 2024-10-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_aamarpaypaymentconfirmation_paymentrequest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReviewModel",
            fields=[
                (
                    "ecommercebasemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ecommerce.ecommercebasemodel",
                    ),
                ),
                ("review", models.TextField()),
                ("rating", models.PositiveIntegerField(default=0)),
                (
                    "cart_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_item_reviews",
                        to="ecommerce.shoppingcartitemmodel",
                    ),
                ),
            ],
            bases=("ecommerce.ecommercebasemodel",),
        ),
    ]
